# Artificial Neural Network

### Importing the libraries

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [0]:
dataset=pd.read_excel('Folds5x2_pp.xlsx')
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values

In [4]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print(Y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0) 

## Part 2 - Building the ANN

### Initializing the ANN

In [0]:
ann=tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=8,activation='relu'))

### Adding the second hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=8,activation='relu'))

### Adding the output layer

In [0]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [0]:
ann.compile(optimizer='adam',loss='mean_squared_error')

### Training the ANN model on the Training set

In [12]:
ann.fit(X_train,Y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 12370.6670
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 299.8664
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 268.4680
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 232.8467
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 195.5256
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 159.3200
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 126.1634
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 97.7243
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 74.4452
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 57.3384
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 45.3534
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 

### Predicting the results of the Test set

In [13]:
Y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[432.94 431.23]
 [464.07 460.01]
 [467.59 461.14]
 ...
 [474.82 473.26]
 [441.55 438.  ]
 [460.79 463.28]]


### Calculating the Root Mean Square Error 

In [14]:
from sklearn.metrics import mean_squared_error
error=mean_squared_error(Y_pred,Y_test)
print(error)

27.46630520746933


# Multiple Linear Regression

In [15]:
from sklearn.linear_model import LinearRegression
regression=LinearRegression()
regression.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the output for test set

In [16]:
Y_lin_pred=regression.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((Y_lin_pred.reshape(len(Y_lin_pred),1), Y_test.reshape(len(Y_test),1)),1))


[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


## Mean Square Error

In [17]:
error_lin=mean_squared_error(Y_test,Y_lin_pred)
print(error_lin)

19.733699303497648
